# Generated by Django 4.0.3 on 2022-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(default=None, null=True, verbose_name='Data do falecimento'),
        ),
    ]
