# Generated by Django 4.0.3 on 2022-04-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_author_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='book',
            name='imprint',
            field=models.CharField(max_length=255, verbose_name='Versão impressa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Linguagem'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Título'),
        ),
    ]
